name:                helio
version:             0.2.0.2
github:              helvm/helio
author:              Kamil Adam
maintainer:          kamil.adam.zabinski@gmail.com
copyright:           2020-2025 Kamil Adam

extra-source-files:
- docs/README.md
- docs/developers/CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/helio#readme>

dependencies:
- base   >= 4.11
- rio    >= 0.1.22.0
- relude >= 1.2.2.2

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
- NoImplicitPrelude
- OverloadedStrings

mixins:
- base hiding (Prelude)
- relude (Relude as Prelude, Relude.Extra)

library:
  source-dirs: hs/src
  dependencies:
    - bytestring
    - containers
    - data-default
    - dlist
    - extra
    - ilist
    - ListLike
    - mono-traversable
    - mtl
    - pretty-simple
    - slist
    - text
    - type-operators

tests:
  helio-test:
    main:                Main.hs
    source-dirs:         hs/test
    dependencies:
    - helio
    - hspec
    - hspec-core
    - hspec-expectations-pretty-diff
    - hspec-golden
    - hspec-slow
    - dlist
    - filepath
    - ListLike
    - mtl
    - stm
    - time
    - type-operators

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
